# Generated by Django 5.1.2 on 2024-11-05 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz_Base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='uploaded_by',
        ),
    ]
