# Generated by Django 5.1.2 on 2024-11-06 04:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz_Base', '0003_document_uploaded_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizSession',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mcqs', models.JSONField()),
                ('user_answers', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
