# Generated by Django 5.1.2 on 2024-11-07 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz_Base', '0005_uploadedpdf'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuizSession',
        ),
    ]
